// SRFI-189 — Maybe & Either. Scheme-bootstrap capability. Source mirrors arrival-scheme/src/bootstrap.ts.
import { EnvCapability } from "../capability.js";

export default new EnvCapability("scheme/srfi-189", {
  prelude: `
(define (just x) (list 'just x))
(define (nothing) (list 'nothing))
(define (left x) (list 'left x))
(define (right x) (list 'right x))
(define (just? m) (and (pair? m) (eq? (car m) 'just)))
(define (nothing? m) (and (pair? m) (eq? (car m) 'nothing)))
(define (maybe? m) (or (just? m) (nothing? m)))
(define (left? e) (and (pair? e) (eq? (car e) 'left)))
(define (right? e) (and (pair? e) (eq? (car e) 'right)))
(define (either? e) (or (left? e) (right? e)))
(define (maybe-ref m . failure)
  (cond ((just? m) (car (cdr m)))
        ((pair? failure) ((car failure)))
        (else (error "maybe-ref: Nothing"))))
(define (maybe-ref/default m default)
  (if (just? m) (car (cdr m)) default))
(define (maybe-bind m f)
  (if (just? m) (f (car (cdr m))) m))
(define (maybe-map f m)
  (if (just? m) (just (f (car (cdr m)))) m))
(define (maybe->list m)
  (if (just? m) (list (car (cdr m))) '()))
(define (list->maybe lst)
  (if (null? lst) (nothing) (just (car lst))))
(define (maybe->either m no-just)
  (if (just? m) (right (car (cdr m))) (left no-just)))
(define (either-ref e . failure)
  (cond ((right? e) (car (cdr e)))
        ((pair? failure) ((car failure) (car (cdr e))))
        (else (error "either-ref: Left"))))
(define (either-ref/default e default)
  (if (right? e) (car (cdr e)) default))
(define (either-bind e f)
  (if (right? e) (f (car (cdr e))) e))
(define (either-map f e)
  (if (right? e) (right (f (car (cdr e)))) e))
(define (either->list e)
  (if (right? e) (list (car (cdr e))) '()))
(define (either-swap e)
  (cond ((left? e) (right (car (cdr e))))
        ((right? e) (left (car (cdr e))))
        (else (error "either-swap: not an Either"))))
`,
});
