// Whitelist of safe built-in functions from LIPS global env
export const SAFE_BUILTINS = [
  // List construction & access
  "cons",
  "car",
  "cdr",
  "list",
  "append",
  "reverse",
  "nth",

  // List predicates
  "empty?",
  "list?",
  "pair?",
  "null?",

  // Higher-order list operations — LIPS native, overridden in sandbox for FL compat
  "map",
  "filter",
  "reduce",
  "for-each",
  "find",
  "apply",

  // Control flow
  "if",
  "let",
  "let*",
  "letrec",
  "lambda",
  "define",
  "begin",
  "and",
  "or",
  "not",
  "quote",
  "do",

  // Math
  "+",
  "-",
  "*",
  "/",
  "abs",
  "sqrt",
  "floor",
  "round",
  "ceiling",
  "truncate",
  "odd?",
  "even?",
  "gcd",
  "lcm",
  "%",
  "**",
  "1+",
  "1-",

  // Comparison
  "==",
  ">",
  "<",
  "<=",
  ">=",
  "eq?",

  // Type checks
  "number?",
  "string?",
  "boolean?",
  "symbol?",
  "function?",
  "array?",
  "object?",
  "null?",
  "regex?",
  "real?",

  // String operations
  "substring",
  "concat",
  "join",
  "split",
  "replace",
  "match",
  "search",
  "string->number",
  "number->string",

  // Exactness conversion
  "exact",
  "inexact",

  // Multiple values
  "let-values",

  // Utility
  "type",
  "clone",
  "values",
  "vector",
  "quasiquote",
  "unquote-splicing",
  "unquote",

  // All the car/cdr variants
  "cadr",
  "caar",
  "cddr",
  "cdar",
  "caddr",
  "caaar",
  "caadr",
  "cadar",
  "cdaar",
  "cdadr",
  "cddar",
  "cdddr",
  "caaaar",
  "caaadr",
  "caadar",
  "caaddr",
  "cadaar",
  "cadadr",
  "caddar",
  "cadddr",

  // SRFI-1 (list library) — pure, added 2026-06-11
  "take-while",
  "drop-while",
  "span",
  "break",
  "partition",
  "find-tail",
  "last-pair",
  "last",
  "list-tabulate",
  "fold-right",
  "reduce-right",
  "concatenate",
  "append-reverse",
  "delete",
  "length+",

  // SRFI-43 (vector library) — pure ops only (arrival vectors are immutable)
  "vector-fold",
  "vector-fold-right",
  "vector-count",
  "vector-index",
  "vector-binary-search",
  "vector-empty?",
  "vector-any",
  "vector-every",

  // SRFI-189 (Maybe & Either)
  "just",
  "nothing",
  "left",
  "right",
  "just?",
  "nothing?",
  "maybe?",
  "left?",
  "right?",
  "either?",
  "maybe-ref",
  "maybe-ref/default",
  "maybe-bind",
  "maybe-map",
  "maybe->list",
  "list->maybe",
  "maybe->either",
  "either-ref",
  "either-ref/default",
  "either-bind",
  "either-map",
  "either->list",
  "either-swap",

  // SRFI-128 (comparators) — no hash (comparator-hashable? always #f)
  "make-comparator",
  "comparator?",
  "comparator-type-test-predicate",
  "comparator-equality-predicate",
  "comparator-ordering-predicate",
  "comparator-hashable?",
  "=?",
  "<?",
  ">?",
  "<=?",
  ">=?",
  "make-default-comparator",
  "default-comparator",

  // Multiple values (call-with-values now promise-correct)
  "call-with-values",

  // SRFI-8 receive + SRFI-2 and-let* (expression macros)
  "receive",
  "and-let*",
];
